spring.application.name=tenant
spring.datasource.url=jdbc:postgresql://localhost:5432/Tenant_Application
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username =postgres
spring.datasource.password=Teja_admin

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=your_secret_key_with_minimum_256_bits_of_entropy_for_security
jwt.expiration=86400000